### ISSUE TITLE
Error: A WebView method was called on thread 'JavaBridge'. 

### ISSUE THREAD

**Issue by AndreRoss** [braintree/popup-bridge-android#10]
### General information

* SDK/Library version: 0.1.1
* Android Version and Device: Android 7.1.1 Pixel XL Android Emulator
### Issue description

The method 'open(String url)' is called in WebviewInterface. The url is https://www.paypal.com/checkoutnow?..&useraction=commit and i get an exception in my webview.

The webview is shown inside a fragment.

java.lang.Throwable: A WebView method was called on thread 'JavaBridge'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {5891226} called on Looper (JavaBridge, tid 621) {a07812e}, FYI main Looper is Looper (main, tid 1) {5891226})
                                                                                at android.webkit.WebView.checkThread(WebView.java:2334)
                                                                                at android.webkit.WebView.evaluateJavascript(WebView.java:1036)
                                                                                at com.braintreepayments.popupbridge.PopupBridge.onBrowserSwitchResult(PopupBridge.java:132)
                                                                                at com.braintreepayments.browserswitch.BrowserSwitchFragment.browserSwitch(BrowserSwitchFragment.java:132)
                                                                                at com.braintreepayments.browserswitch.BrowserSwitchFragment.browserSwitch(BrowserSwitchFragment.java:107)
                                                                                at com.braintreepayments.popupbridge.PopupBridge.open(PopupBridge.java:148)

**Comment by crookedneighbor** [comment]
It looks like [JavaScript evaluation](https://github.com/braintree/popup-bridge-android/blob/42e49aecb918cc4a845b595e7fde9109e58d7ef0/PopupBridge/src/main/java/com/braintreepayments/popupbridge/PopupBridge.java#L132) is not always happening on the correct thread and needs to be wrapped in a `Looper`/`Handler`.

We'll make this fix unless you'd like to submit a PR for it.
